# TODO:load from ~/.config/mcp-client-console/config.toml
    # right now config.toml gets loaded in with the pipx install mcp-client-console......... but every update or reinstall it wipes back to normal. need a real constant config file somewhere, gotta figure this out where it goes etc...
