# __init__.py
# llm_shepherd: a drop-in supervisor that keeps small local models on task during
# agentic tool loops. Add-only companion to the llm/ package - wraps the provider,
# edits nothing. See README.md in this folder for the two-line wire-in.
#
# EXTERNAL PACKAGE (vendored): designed and generated by Claude Fable 5 (Anthropic),
# 2026-07-09. NOT hand-written by this repository's author - see README.md provenance.

from mcp_client_console._vendor.llm_shepherd.policy import Policy
from mcp_client_console._vendor.llm_shepherd.shepherd import Shepherd, attach

__version__ = "0.1.0"
__all__ = ["attach", "Shepherd", "Policy", "__version__"]
